#!/usr/bin/env bash

# Change to the directory where the script is called from
# This ensures we're in the right project context for PDM
cd "$(pwd)"

# find your global npm “root” directory
NPM_BIN=$(npm root -g)

# exec the shebang script directly
exec python -m pdm run node "${NPM_BIN}/pyright/langserver.index.js" "$@"
